### ISSUE TITLE
Nexus 1.1.0 doesn't work with last graphql package 

### ISSUE THREAD

**Issue by Zelleaz** [graphql-nexus/nexus#1025]
I was learning nexus and doing these steps:
1)  npm install nexus graphql 
2) Write some code (it works by the way)

By default "npm install graphql" will install graphql ^16.1.0 (for a moment of writing this issue) 
But it doesn't work and I got this error:
```
TypeError: Class constructor GraphQLNonNull cannot be invoked without 'new'
    at SchemaBuilder.missingType (/home/zelleaz/Projects/mui/server/node_modules/nexus/src/builder.ts:1099:19)
    at SchemaBuilder.getOrBuildType (/home/zelleaz/Projects/mui/server/node_modules/nexus/src/builder.ts:1448:17)
    at /home/zelleaz/Projects/mui/server/node_modules/nexus/src/builder.ts:794:37
    at Array.forEach (<anonymous>)
    at SchemaBuilder.buildNexusTypes (/home/zelleaz/Projects/mui/server/node_modules/nexus/src/builder.ts:782:38)
    at SchemaBuilder.getFinalTypeMap (/home/zelleaz/Projects/mui/server/node_modules/nexus/src/builder.ts:835:10)
    at Object.makeSchemaInternal (/home/zelleaz/Projects/mui/server/node_modules/nexus/src/builder.ts:1684:92)
    at makeSchema (/home/zelleaz/Projects/mui/server/node_modules/nexus/src/makeSchema.ts:14:49)
    at Object.<anonymous> (/home/zelleaz/Projects/mui/server/index.ts:11:33)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
```

I tried to use graphql 14.5.8 and it solved the problem. But anyway nexus didn't work correctly with the last version of graphql npm package :(

**Comment by Zelleaz** [comment]
I read that someone uses nexus 1.2.0, but how? I mean, in this Github repo 1.1.0 is the latest release

**Comment by PatrykWalach** [comment]
you can install a pre-release under a `next` tag
```sh
npm i nexus@next
```

**Comment by saevarb** [comment]
I am having this issue as well after updating to 1.1.0, and it seems several other people are as well, but there has yet to be a single response from any maintainer. 

It seems installing the 1.2.0-next.17 version fixes this, but there is zero information about this anywhere, nor whether this version is actually ready for production use.

Can we get a response from the developers? @tgriesser @jasonkuhrt A recommended workaround would be great
