### ISSUE TITLE
Prettier error occurred when use schema in jest

### ISSUE THREAD

**Issue by aya-eiya** [graphql-nexus/nexus#1052]
When I refer to a schema object created by createSchema with prettier config from jest, I get a prettier error.

```console
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From tests/jest.test.ts.

      at Object.get graphql [as graphql] (node_modules/prettier/index.js:53298:12)
      at resolveParser$1 (node_modules/prettier/index.js:12937:21)
      at normalize$1 (node_modules/prettier/index.js:13048:18)
      at formatWithCursor$1 (node_modules/prettier/index.js:14746:46)
      at node_modules/prettier/index.js:60959:12
  console.error
    TypeError: Cannot read property 'graphql' of undefined
        at Object.get graphql [as graphql] (/ws/nenux-gql-prettier-error/node_modules/prettier/index.js:53298:50)
        at resolveParser$1 (/ws/nenux-gql-prettier-error/node_modules/prettier/index.js:12937:21)
        at normalize$1 (/ws/nenux-gql-prettier-error/node_modules/prettier/index.js:13048:18)
        at formatWithCursor$1 (/ws/nenux-gql-prettier-error/node_modules/prettier/index.js:14746:46)
        at /ws/nenux-gql-prettier-error/node_modules/prettier/index.js:60959:12
        at Object.format (/ws/nenux-gql-prettier-error/node_modules/prettier/index.js:60979:12)
        at /ws/nenux-gql-prettier-error/node_modules/nexus/src/typegenFormatPrettier.ts:40:21
        at Generator.next (<anonymous>)
        at fulfilled (/ws/nenux-gql-prettier-error/node_modules/tslib/tslib.js:114:62)

      at node_modules/nexus/src/makeSchema.ts:43:17

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

versions:
```json
  "dependencies": {
    "graphql": "^15.8.0",
    "nexus": "^1.2.0"
  },
  "devDependencies": {
    "@types/jest": "^27.4.0",
    "@types/node": "^14.18.10",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-jest": "^26.0.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint": "^8.8.0",
    "jest": "^27.4.7",
    "prettier": "^2.5.1",
    "ts-jest": "^27.1.3",
    "typescript": "^4.5.5"
  }
```

Here is the error regeneration project.
https://github.com/aya-eiya/nenux-gql-prettier-error

**Comment by calirvine** [comment]
I believe this is because `makeSchema()` is still running the reflection step. By adding a small delay to the test you can test that this is the problem:
```
const wait = (delay: number) =>
  new Promise((resolve) => setTimeout(resolve, delay))
  
describe('ref schema', () => {
  it('access schema variable', async () => {
    await wait(1000)
    expect(schema).toBeDefined()
  })
})
```

I think skipping generating artifacts in process.env.NODE_ENV === test should be the right move (actually I think you only want to generate in development, or in your prebuild step).
```
makeSchema({
  shouldGenerateArtifacts: process.env.NODE_ENV === 'development',
  ... // the rest of your config
});
```

**Comment by aya-eiya** [comment]
Thanks for the answer!
I will check on my sample project.
