### ISSUE TITLE
Cannot read property <field> of undefined when using `t.field`

### ISSUE THREAD

**Issue by talentlessguy** [graphql-nexus/nexus#895]
## The problem

Hello, I'm trying to add a custom Nexus mutation field to increment user and post views count easily but I'm struggling to figure out what's wrong in there.

Weird thing here is that I have already defined one of the fields previously and it worked just fine:

```ts
t.crud.createOnePost({ alias: 'createPost' })

t.field('createPost', {
  type: 'Post',
  args: {
    data: arg({
      type: 'PostCreateInput'
    })
  },
  shield: shield(),
  resolve: async (_, { data }, ctx) => {
    return await ctx.prisma.post.create({
      data
    })
  }
})
```

but trying to do something similar but for a updating a post / user view counter results in an error :\

## Error message

```
TypeError: Cannot read property 'updateViews' of undefined
    at PicPage (webpack-internal:///./pages/[slug]/pic/[id].tsx:76:20)
    at processChild (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (webpack-internal:///./node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/pages/_document.js:141:19)
    at loadGetInitialProps (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/server/render.js:54:1145)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /home/v1rtl/Coding/picstatic/node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /home/v1rtl/Coding/picstatic/node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/home/v1rtl/Coding/picstatic/node_modules/.pnpm/next@10.1.3_507781d099a67956587e23f5ac79078b/node_modules/next/dist/next-server/server/next-server.js:138:923)
Failed to parse source map: TypeError [ERR_INVALID_URL]: Invalid URL: webpack://[id].tsx

```

## Client-side code

Here is how my client-side mutation code looks like (**pages/[slug]/[id].tsx**):

```ts
import React, { useEffect } from 'react'
import { GetServerSideProps, NextPage } from 'next'
import { gql, useMutation } from '@apollo/client'
import { initializeApollo } from 'lib/apollo'
import { updateViews, updateViewsVariables } from 'generated/updateViews'

const UPDATE_VIEWS = gql`
  mutation updateViews($userId: Int!, $id: Int!) {
    updateViews(id: $id, userId: $userId) {
      views
      image {
        secureUrl
      }
      caption
      views
      author {
        name
        image
      }
    }
  }
`

const PicPage: NextPage<Props> = ({ id, userId }) => {
  const [mutate, { data: { updateViews: post } }] = useMutation<updateViews>(UPDATE_VIEWS, { variables: { id, userId } as updateViewsVariables })
  // ...
}

export const getServerSideProps: GetServerSideProps = async ({ query, req }) => {
  const apollo = initializeApollo()

  const { data: { user } } = await apollo.query({
    query: gql`
      query getUserBySlug($slug: String) {
        user(where: { slug: $slug }) {
          id
        }
      }
    `,
    variables: { slug: query.slug }
  })

  const { data: { updateViews: post } } = await apollo.mutate<updateViews>({
    mutation: UPDATE_VIEWS,
    variables: { id: parseInt(query.id as string, 10), userId: user.id } as updateViewsVariables
  })

  return {
    props: {
      initialApolloState: apollo.cache.extract(),
      id: parseInt(query.id as string, 10),
      userId: user.id
    }
  }
}

export default PicPage
```

**apollo.ts**:

```ts
import { useMemo } from 'react'
import { ApolloClient, InMemoryCache, ApolloLink } from '@apollo/client'
import { HttpLink } from '@apollo/client/link/http'
import { onError } from '@apollo/client/link/error'

let apolloClient: ReturnType<typeof createApolloClient>

const errorLink = onError(({ graphQLErrors }) => {
  if (graphQLErrors) graphQLErrors.map(({ message }) => console.log(message))
})

const createIsomorphLink = () =>
  new HttpLink({
    uri: typeof window === 'undefined' ? 'http://localhost:3000/api/graphql' : '/api/graphql',
    credentials: 'same-origin'
  })

export const createApolloClient = () =>
  new ApolloClient({
    ssrMode: typeof window === 'undefined',
    link: ApolloLink.from([errorLink, createIsomorphLink()]),
    cache: new InMemoryCache()
  })

export function initializeApollo(initialState = null) {
  const _apolloClient = apolloClient ?? createApolloClient()

  if (initialState) {
    const existingCache = _apolloClient.extract()

    _apolloClient.cache.restore({ ...existingCache, ...initialState })
  }

  if (typeof window === 'undefined') return _apolloClient

  if (!apolloClient) apolloClient = _apolloClient
  return _apolloClient
}

export function useApollo<T>(initialState: T) {
  const store = useMemo(() => initializeApollo(initialState), [initialState])
  return store
}
```

## Server-side code

and here is my **resolvers.ts** file:

```ts
import { arg,  objectType, queryType } from 'nexus'

export const Query = queryType({
  definition(t) {
    t.crud.posts()
    t.crud.post()
    t.crud.user()
  }
})

export const Post = objectType({
  name: 'Post',
  definition(t) {
    t.model.author()
    t.model.caption()
    t.model.createdAt()
    t.model.image()
    t.model.views()
  }
})

export const Mutation = mutationType({
  definition(t) {
    t.crud.createOneUser()
    // This one breaks
    t.field('updateViews', {
      type: 'Post',
      args: {
        id: arg({ type: 'Int' }),
        userId: arg({ type: 'Int' })
      },
      resolve: async (_, { userId, id }, ctx) => {
        // Update user as well
        await ctx.prisma.user.update({
          data: { views: { increment: 1 } },
          where: { id: userId }
        })

        return await ctx.prisma.post.update({
          data: { views: { increment: 1 } },
          where: { id }
        })
      }
    })
  }
})
```

**schema.ts**:

```ts
import { makeSchema } from 'nexus'
import { nexusPrisma } from 'nexus-plugin-prisma'
import path from 'path'
import { Mutation, Post, Query } from './resolvers'

export const schema = makeSchema({
  types: [Query, Post, Mutation],
  contextType: {
    module: path.join(process.cwd(), 'graphql', 'context.ts'),
    export: 'Context'
  },

  plugins: [
    nexusPrisma({
      experimentalCRUD: true,
      outputs: { typegen: path.join(process.cwd(), 'generated', 'typegen-nexus-plugin-prisma.d.ts') }
    }),
  ],
  outputs: {
    typegen: path.join(process.cwd(), 'generated', 'nexus-typegen.ts'),
    schema: path.join(process.cwd(), 'generated', 'schema.graphql')
  }
})
```

## Useful info

- `node -v`: v15.12

- **package.json**:

```json
"nexus": "^1.0.0",
"nexus-plugin-prisma": "^0.33.0",
"graphql": "^15.5.0",
"next": "^10.1.3",
"@prisma/client": "^2.21.2",
"apollo-server-micro": "^3.0.0-alpha.3",
"prisma": "^2.21.2"
```

**Comment by talentlessguy** [comment]
nevermind, it was a client-side issue

i tried to access a prop on mutation data that hasn't been fulfilled yet
