### ISSUE TITLE
nullable return type breaks my code

### ISSUE THREAD

**Issue by heddendorp** [graphql-nexus/nexus#993]
I created a field with the following definition
```
t.field({
      name: 'openMoveOrder',
      type: nullable(moveOrderType),
      resolve: (source, args, context) =>
        context.prisma.eventRegistrationMoveOrder.findFirst({
          where: { registration: { id: source.id }, usedBy: { not: null } },
        }),
    });
```

When running my app though, I get an error that only occurs when having this code.
```
[...]\node_modules\nexus\src\utils.ts:620
    return Boolean(Object.getOwnPropertyDescriptor(obj, key))
                          ^
TypeError: Cannot convert undefined or null to object
```

my best guess is that nexus is not handling the possible null value returned here

**Comment by villesau** [comment]
Something like this happens to me too. The error message is not very helpful to pinpoint what's going on. This happened when I made some drastic changes to my prisma schema (i'm using nexus-prisma). Below is the stack trace:

```
/node_modules/nexus/src/utils.ts:620
    return Boolean(Object.getOwnPropertyDescriptor(obj, key))
                          ^
[generate:server-graphql] TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptor (<anonymous>)
    at Object.has (/Users/repo/node_modules/nexus/src/utils.ts:620:27)
    at isNexusMetaTypeProp (/Users/repo/node_modules/nexus/src/definitions/nexusMeta.ts:39:18)
    at Object.isNexusMetaType (/Users/repo/node_modules/nexus/src/definitions/nexusMeta.ts:35:10)
    at Object.getNexusNamedType (/Users/repo/node_modules/nexus/src/utils.ts:544:73)
    at SchemaBuilder.maybeTraverseOutputFieldType (/Users/repo/node_modules/nexus/src/builder.ts:1592:28)
    at Object.addField (/Users/repo/node_modules/nexus/src/builder.ts:1549:29)
    at ObjectDefinitionBlock.field (/Users/repo/node_modules/nexus/src/definitions/definitionBlocks.ts:724:22)
    at Object.definition (/Users/repo/src/server/graphql/ModelName/index.ts:30:7)
    at SchemaBuilder.walkOutputType (/Users/repo/node_modules/nexus/src/builder.ts:1554:9)

```

The actual error is on `at Object.definition (/Users/repo/src/server/graphql/ModelName/index.ts:30:7)` which I believe should be highlighted in the error message somehow too.

the line that failed passed undefined to the `t.field`: `t.field(ModelName.thisFieldIsActuallyUndefined);`

So: Would it be possible to detect such cases and throw more informative error? This happens easily when refactoring schemas.

**Comment by iquabius** [comment]
I got this cryptic error:

`TypeError: Cannot convert undefined or null to object`

It took quite a bit of time to pinpoint where I made the mistake because there was a lot of changes in my current branch.

What I did was move some imports to the end of an `index.ts` because they were being deprecated:

```diff
-export * from "./LoginVerifySuccess"
-export * from "./LoginVerifyProblem"
 export * from "./UserStaff"
+
+// My mistake  <------
+// UserStaff should be exported last because it depends on the other 2  🤦
+
+// Deprecated
+export * from "./LoginVerifySuccess"
+export * from "./LoginVerifyProblem"
```

I'm passing objects directly instead of names. That's another reason why I get the error:

```ts
// Definition for LoginVerifyResult union
t.members(
  LoginVerifySuccess,
  LoginVerifyProblem,
)
```
